
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: false
    health:
      show-details: ALWAYS

---
spring:
  profiles: production
 

logstash:
   host: logstash:5000
