server:
  port: 8761
  

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    server:
      waitTimeInMsWhenSyncEmpty: 0
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

    
---
spring:
  profiles: production

eureka:
  client:
    serviceUrl:
      defaultZone: http://flight-management-discovery-service:8761/eureka
  instance:
    preferIpAddress: true
